version: '3'

volumes:
  pgdata:

services:
  gwap_auth:
    image: gwap-auth:latest
    container_name: gwap-auth
    build: .
    expose:
    - 8080
    ports:
    - 8080:8080
    env_file:
    - environments/hml.env
